apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/managed-by: edp-grub
    app.kubernetes.io/name: edp-grub  # tenant name - configurable and must be uniq in cluster
    app.edp.epam.com/tenant: edp-grub # tenant name - configurable and must be uniq in cluster
  name: grub-keycloak
  namespace: argocd
spec:
  project: default  # provision Keycloak Groups to be used by ArgoCD

  source:
    path: apps-configs/grub/keycloak
    repoURL: git@github.com:SergK/edp-grub.git
    targetRevision: main
    directory:
      jsonnet: {}
      recurse: true

  destination:
    namespace: edp-delivery-sk-delivery-dev   # EDP namespace, since keycloak operator is here
    server: https://kubernetes.default.svc

  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false

  ignoreDifferences:
  - group: argoproj.io
    jsonPointers:
    - /status
    kind: Application
